version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "buildSrc/src/main/java/Libraries.kt" }}-{{ checksum  "buildSrc/src/main/java/configs/KotlinConfig.kt" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies --no-daemon
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "buildSrc/src/main/java/Libraries.kt" }}-{{ checksum  "buildSrc/src/main/java/configs/KotlinConfig.kt" }}
      - run:
          name: Setup env
          command: export IS_CI_BUILD="true"
      - run:
          name: Check code style
          command: ./gradlew clean ktlintCheck --no-daemon
      - run:
          name: Run Tests
          command: ./gradlew clean test --no-daemon
      - run:
          name: Assemble Debug APK
          command: ./gradlew clean assembleDebug -xlint -PdisablePreDex --no-daemon
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - store_test_results:
          path: app/build/test-results
