name: Main

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Project Checkout
        uses: actions/checkout@v2.3.1

      - name: Compute key for CI cache
        run: ./compute-ci-cache-key.sh key.txt

      - name: Setup cache
        uses: actions/cache@v2.1.0
        continue-on-error: true
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('key.txt') }}
          restore-keys: ${{ runner.os }}-gradle-
      
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1.4.0
        with:
          java-version: 1.8

      - name: Copy CI gradle.properties
        run: |
          mkdir -p ~/.gradle
          cp .github/githubci-gradle.properties ~/.gradle/gradle.properties

      - name: Resolve dependencies
        run: ./gradlew androidDependencies --no-daemon --stacktrace

      - name: Check code formatting
        run: ./gradlew ktlintCheck --no-daemon --stacktrace

      - name: Check code smells
        run: ./gradlew detekt --no-daemon --stacktrace

      - name: Run tests and collect reports
        run: ./gradlew clean jacocoTestReport jacocoTestReportDebug --no-daemon

      - name: Upload test reports to Codecov
        uses: codecov/codecov-action@v1.0.12

      - name: Assemble APK
        run: ./gradlew assembleDebug -xlint --no-daemon --stacktrace